"""
Utils Module for Mystic Trading Platform

Contains utility functions and classes for the application.
"""

from .exceptions import (
    AIError,
    AIException,
    APIError,
    APIException,
    AuthenticationError,
    AuthenticationException,
    DatabaseConnectionError,
    DatabaseConnectionException,
    DatabaseError,
    DatabaseException,
    ErrorCode,
    MarketDataError,
    MarketDataException,
    ModelError,
    ModelException,
    MysticException,
    NotificationError,
    NotificationException,
    RateLimitError,
    RateLimitException,
    StrategyError,
    StrategyException,
    TradingError,
    TradingException,
    create_http_exception_handler,
    handle_async_exception,
    handle_exception,
    safe_async_execute,
    safe_execute,
)

__all__ = [
    "AIError",
    "AIException",
    "APIError",
    "APIException",
    "AuthenticationError",
    "AuthenticationException",
    "DatabaseConnectionError",
    "DatabaseConnectionException",
    "DatabaseError",
    "DatabaseException",
    "ErrorCode",
    "MarketDataError",
    "MarketDataException",
    "ModelError",
    "ModelException",
    "MysticException",
    "NotificationError",
    "NotificationException",
    "RateLimitError",
    "RateLimitException",
    "StrategyError",
    "StrategyException",
    "TradingError",
    "TradingException",
    "create_http_exception_handler",
    "handle_async_exception",
    "handle_exception",
    "safe_async_execute",
    "safe_execute",
]
